remote_theme: "owasp/www--site-theme@main"
plugins:
 - jekyll-include-cache-0.2.0

collections:
  tabs:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: tab
